language: java
jdk:
  - oraclejdk11
  - openjdk11
os:
  - linux
  - osx

script:
- mvn clean package
after_success:
- mvn jacoco:report coveralls:report
- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN